var T = new ActiveXObject("ASCOM.INDIGO.Mount");
T.SetupDialog();
T.Connected = true;
T.TrackingRate = 0;
WScript.StdOut.WriteLine("TrackingRate = " + T.TrackingRate);
T.TrackingRate = 1;
WScript.StdOut.WriteLine("TrackingRate = " + T.TrackingRate);
T.TrackingRate = 2;
WScript.StdOut.WriteLine("TrackingRate = " + T.TrackingRate);
T.TrackingRate = 0;
WScript.StdOut.WriteLine("TrackingRate = " + T.TrackingRate);
WScript.StdIn.ReadLine();
T.MoveAxis(0, 1);
WScript.StdIn.ReadLine();
T.MoveAxis(0, -1);
WScript.StdIn.ReadLine();
T.MoveAxis(0, 0);
WScript.StdIn.ReadLine();
T.MoveAxis(1, 1);
WScript.StdIn.ReadLine();
T.MoveAxis(1, -1);
WScript.StdIn.ReadLine();
T.MoveAxis(1, 0);
